### ISSUE TITLE
Editing gods.js not working when I paste the json in the web app

### ISSUE THREAD

**Issue by palla89** [sharkson/smitebuilder#1]
Hi! I tried to paste the gods.js with some modifications but it doesn't work:

![unknown-2](https://user-images.githubusercontent.com/12301205/77248927-a7aa9280-6c3d-11ea-8b92-8209f581e649.png)

It's a valid json, I also tried with the original gods.js you put here but the error is the same

**Comment by sharknice** [comment]
there was an extra comma in there making it invalid json.  It's fixed now.
