### ISSUE TITLE
Masks not showing up when they should

### ISSUE THREAD

**Issue by RodrigueLemaire** [sharkson/smitebuilder#13]
Lono's Mask shows up for everyone, when it should only for mages, assassins and hunters.
Rangda's Mask doesn't show up on warriors where it should.
Bumba's doesn't show for everyone and misses magical power.

I fixed all in #14

**Comment by azekillDIABLO** [comment]
I have no clue which part of the code handles that. I will take a closer look.

**Comment by azekillDIABLO** [comment]
Bumba's mask misses magical power value
