### ISSUE TITLE
Use float instead of int for some item stats.

### ISSUE THREAD

**Issue by tj-thornsberry** [sharkson/smitebuilder#2]
I'm in the process of updating the item list and stats, and I've noticed items like Charon's Coin has +20% (.20) Magical Penetration, while most things like Divine Ruin have +15 Magical Penetration.
I hadn't seen anywhere on the item updater to switch between percentage and whole numbers.

**Comment by sharknice** [comment]
The Item updater has been updated to include magical penetration % and physical penetration %.  The % pen fields separate from the flat pen fields.

**Comment by tj-thornsberry** [comment]
Alright, thank you, how would that look in the JS files as I'm scraping the stats to update everything.

**Comment by sharknice** [comment]
"magicalPenetration": 10,
"magicalPenetrationPercent": 15,
"physicalPenetration": 10,
"physicalPenetrationPercent": 15,

**Comment by tj-thornsberry** [comment]
Thank you again.

**Comment by sharknice** [comment]
If you're scraping data you may find this useful.  These python scripts are what I used to originally scrape the stats.  They're not perfect though.  I had to make changes to the data after scraping. I also used VS Code to "Format Document" to beautify the json.  
https://github.com/sharknice/SmiteScraper

**Comment by tj-thornsberry** [comment]
Well then.. that was a night of coding wasted.. 
Also to beautify the json file in python I just use:
`with open(file_location, "w") as jsonFile:
json.dump(new_json, jsonFile, indent=4)`
